//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Contact
    {
        [DisplayName("آیدی")]
        public int CoID { get; set; }
        [DisplayName("نام کامل")]
        public string Name { get; set; }
        [DisplayName("ایمیل")]
        public string Email { get; set; }
        [DisplayName("موضوع")]
        public string Subject { get; set; }
        [DisplayName("پیغام")]
        public string Message { get; set; }
        [DisplayName("برچسب زمانی")]
        public string Timestamp { get; set; }
    }
}
