//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FAContent
    {
        [Display(Name = "کد محتوا")]
        public int CID { get; set; }
        [Display(Name = "عنوان محتوا")]
        public string title { get; set; }
        [Display(Name = "محتوای اصلی")]
        public string content { get; set; }
    }
}
