//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class FAContent
    {
        [DisplayName("آیدی")]
        public int CID { get; set; }
        [DisplayName("عنوان")]
        public string title { get; set; }
        [DisplayName("محتوا")]
        public string content { get; set; }
    }
}
