//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class FAProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAProduct()
        {
            this.Orders = new HashSet<Order>();
        }

        [DisplayName("آیدی محصول")]
        public int PID { get; set; }
        [DisplayName("عنوان")]
        public string Title { get; set; }
        [DisplayName("خلاصه")]
        public string Summary { get; set; }
        [DisplayName("توضیحات")]
        public string Description { get; set; }
        [DisplayName("قیمت")]
        public int Price { get; set; }
        [DisplayName("وضعیت")]
        public string Status { get; set; }
        [DisplayName("موجودی")]
        public int Qty { get; set; }
        [DisplayName("آدرس عکس")]
        public string Imagepath { get; set; }
        [DisplayName("دسته بندی")]
        public Nullable<int> CATID { get; set; }

        
        public virtual FACategory FACategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
