//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FATeam
    {
        [Display(Name = "کد تیم")]
        public int TEAMID { get; set; }
        [Display(Name = "توضیحات")]
        public string Content { get; set; }
        [Display(Name = "آدرس عکس اصلی")]
        public string ImgUrl { get; set; }
    }
}
