//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FAUser
    {
        [Display(Name = "کد عضویت")]
        public int UID { get; set; }
        [Display(Name = "نام کامل")]
        public string Fullname { get; set; }
        [Display(Name = "نام کاربری")]
        public string Username { get; set; }
        [Display(Name = "رمزعبور")]
        public string Password { get; set; }
        [Display(Name = "ایمیل")]
        public string Email { get; set; }
        [Display(Name = "بیو")]
        public string Bio { get; set; }
        [Display(Name = "تیم")]
        public string Team { get; set; }
        [Display(Name = "نقش")]
        public string Type { get; set; }
        [Display(Name = "آدرس عکس پروفایل")]
        public string Imagepath { get; set; }
    }
}
