//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class FAUser
    {
        [DisplayName("آیدی")]
        public int UID { get; set; }
        [DisplayName("نام کامل")]
        public string Fullname { get; set; }
        [DisplayName("نام کاربری")]
        public string Username { get; set; }
        [DisplayName("رمز عبور")]
        public string Password { get; set; }
        [DisplayName("ایمیل")]
        public string Email { get; set; }
        [DisplayName("بیو")]
        public string Bio { get; set; }
        [DisplayName("تیم")]
        public string Team { get; set; }
        [DisplayName("نقش")]
        public string Type { get; set; }
        [DisplayName("آدرس عکس پروفایل")]
        public string Imagepath { get; set; }
    }
}
