//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feature
    {
        [Display(Name = "کد ویژگی")]
        public int FID { get; set; }
        [Display(Name = "عنوان ویژگی")]
        public string Title { get; set; }
        [Display(Name = "قیمت")]
        public string Price { get; set; }
        [Display(Name = "دسته")]
        public string Cate { get; set; }
        [Display(Name = "کد محصول")]
        public Nullable<int> PID { get; set; }
        [Display(Name =  "محصول")]
        public virtual FAProduct FAProduct { get; set; }
    }
}
