//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VIRADB : DbContext
    {
        public VIRADB()
            : base("name=VIRADB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ENContent> ENContents { get; set; }
        public virtual DbSet<ENProduct> ENProducts { get; set; }
        public virtual DbSet<ENUser> ENUsers { get; set; }
        public virtual DbSet<FAContent> FAContents { get; set; }
        public virtual DbSet<FAProduct> FAProducts { get; set; }
        public virtual DbSet<FAUser> FAUsers { get; set; }
        public virtual DbSet<OrderAddress> OrderAddresses { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
