//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFeature
    {
        public int OFID { get; set; }
        public Nullable<int> OID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> FID { get; set; }
    
        public virtual FAProduct FAProduct { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Order Order { get; set; }
    }
}
