//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrderAddress
    {
        [DisplayName("آیدی")]
        public int AID { get; set; }
        [DisplayName("نام کامل")]
        public string Name { get; set; }
        [DisplayName("استان")]
        public string Ostan { get; set; }
        [DisplayName("شهر")]
        public string City { get; set; }
        [DisplayName("آدرس")]
        public string Address { get; set; }
        [DisplayName("شماره تلفن")]
        public string Phone { get; set; }
        [DisplayName("ایمیل")]
        public string Email { get; set; }
        [DisplayName("کدپستی")]
        public string Codeposti { get; set; }
        [DisplayName("شماره سبد")]
        public Nullable<int> Cartid { get; set; }
        public Nullable<int> OID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
