//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Service
    {
        [Display(Name = "کد سرویس")]
        public int SID { get; set; }
        [Display(Name = "نام سرویس")]
        public string title { get; set; }
        [Display(Name = "محتوا")]
        public string content { get; set; }
    }
}
