//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Slider
    {
        [Display(Name = "کد عکس")]
        public int SLID { get; set; }
        [Display(Name = "آدرس عکس")]
        public string ImgUrl { get; set; }
        [Display(Name = "توضیحات")]
        public string Caption { get; set; }
        [Display(Name = "لینک عکس")]
        public string ImgLink { get; set; }
    }
}
