//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ourmsmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SLID { get; set; }
        public string ImgUrl { get; set; }
        public string Caption { get; set; }
        public string ImgLink { get; set; }
    }
}
